export default () => ({
  NODE_ENV: process.env.NODE_ENV ?? 'development',
  API_PORT: parseInt(process.env.API_PORT ?? '3000', 10),
  API_GLOBAL_PREFIX: process.env.API_GLOBAL_PREFIX ?? 'api/v1',
  DATABASE_URL: process.env.DATABASE_URL,
  REDIS_URL: process.env.REDIS_URL,
  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN ?? '15m',
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN ?? '7d',
  APP_PUBLIC_URL: process.env.APP_PUBLIC_URL ?? 'http://localhost:3000',
  ADMIN_PUBLIC_URL: process.env.ADMIN_PUBLIC_URL ?? 'http://localhost:3001',
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_PRICE_MONTHLY_PREMIUM: process.env.STRIPE_PRICE_MONTHLY_PREMIUM,
  STRIPE_TRIAL_DAYS: parseInt(process.env.STRIPE_TRIAL_DAYS ?? '7', 10),
  S3_ENDPOINT: process.env.S3_ENDPOINT,
  S3_REGION: process.env.S3_REGION ?? 'us-east-1',
  S3_BUCKET: process.env.S3_BUCKET,
  S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
  S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
  S3_PUBLIC_BASE_URL: process.env.S3_PUBLIC_BASE_URL,
  CORS_ORIGINS: process.env.CORS_ORIGINS ?? '',
});
